"""
main.py - Hybrid Stock Analyst CLI Orchestrator
================================================
PURPOSE:
  The single entry point for the entire system.
  Coordinates: Scraping -> Rule Evaluation -> Notion Sync -> Report

HOW MODEL SWITCHING WORKS:
  Phase 1 (Data)        : Runs locally via Python (scraper + rule engine)
  Phase 2 (Math/Calc)  : Antigravity (Gemini Pro) — deep reading, pattern recognition
  Phase 3 (Synthesis)  : Antigravity summarizes and gives final verdict with reasoning

USAGE:
  python src/main.py analyze HDFCBANK
  python src/main.py analyze HDFCBANK --portfolio 1500000
  python src/main.py analyze HDFCBANK --login          (force re-login to Tijori)
  python src/main.py watchlist                          (show all watchlisted stocks)
  python src/main.py ledger                             (show portfolio)
  python src/main.py add-position HDFCBANK 1800 10     (add to ledger: symbol price qty)
  python src/main.py demo HDFCBANK                     (demo with mock data, no browser)
"""

import asyncio
import json
import sys
import os
from pathlib import Path
from datetime import datetime

BASE_DIR = Path(__file__).parent.parent
sys.path.insert(0, str(BASE_DIR / "src"))

from rule_engine import RuleEngine
from notion_sync import NotionSync

TIJORI_SCRIPT = BASE_DIR / "skills" / "tijori" / "scripts" / "scrape_tijori.py"
TIJORI_EXPLORE = BASE_DIR / "skills" / "tijori" / "scripts" / "explore_tijori.py"
TIJORI_REGISTRY = BASE_DIR / "skills" / "tijori" / "scripts" / "selector_registry.json"

OUTPUT_DIR = BASE_DIR / "output"
MEMORY_DIR = BASE_DIR / "memory"
BUNDLES_DIR = OUTPUT_DIR / "bundles"
REPORTS_DIR = OUTPUT_DIR / "reports"
LEDGER_DIR = MEMORY_DIR / "ledger"


# ── Utility Functions ─────────────────────────────────────────────────────────

def load_latest_bundle(symbol: str) -> dict | None:
    """Load the most recent scraped JSON for a given symbol."""
    symbol = symbol.upper()
    files = sorted(BUNDLES_DIR.glob(f"{symbol}_*.json"), reverse=True)
    if not files:
        return None
    with open(files[0], encoding="utf-8") as f:
        return json.load(f)


def load_mock_data(symbol: str) -> dict:
    """Generate mock data for demo/testing without running the browser."""
    return {
        "symbol": symbol.upper(),
        "scraped_at": datetime.now().isoformat(),
        "source": "mock_demo",
        "price_data": {
            "current_price": 1850.0,
            "52w_high": 1960.0,
            "52w_low": 1380.0,
            "dma_50": 1810.0,
            "dma_150": 1720.0,
            "dma_200": 1680.0,
            "rsi": 62.4,
            "volume_vs_avg_pct": 55.0,
            "macd_signal": "bullish_crossover"
        },
        "ratios": {
            "p_e": "19.2",
            "market_cap": "13,45,000 Cr",
            "roe": "16.8",
            "roce": "14.2",
            "debt_to_equity": "0.62",
            "profit_growth": "28.5",
            "sales_growth": "17.3",
            "rs_rating": "72"
        },
        "shareholding": {
            "promoter": 26.1,
            "fii": 21.4,
            "dii": 18.9,
            "public": 33.6
        },
        "financials": {}
    }


def generate_report_markdown(symbol: str, result: dict, data: dict) -> str:
    """Generate a full markdown report for the analysis."""
    ts = datetime.now().strftime("%d-%b-%Y %H:%M")
    lines = [
        f"# Stock Analysis Report: {symbol}",
        f"**Date:** {ts}  |  **Source:** {data.get('source', 'N/A')}",
        "",
        "---",
        "",
        f"## VERDICT: {result['verdict']}",
        f"**Composite Score: {result['score']}/100**",
        "",
        "| Component | Score | Weight |",
        "|-----------|-------|--------|",
        f"| Trend Template | {result['trend_score']}/100 | 35% |",
        f"| Fundamentals | {result['fundamental_score']}/100 | 35% |",
        f"| Technicals | {result['technical_score']}/100 | 30% |",
        "",
        "---",
        "",
        "## Strengths",
    ]

    for s in result.get("strengths", []):
        lines.append(f"- {s}")

    lines += ["", "## Weaknesses"]
    for w in result.get("weaknesses", []):
        lines.append(f"- {w}")

    if result.get("risk_flags"):
        lines += ["", "## Risk Flags"]
        for rf in result["risk_flags"]:
            lines.append(f"- {rf}")

    lines += [
        "",
        "---",
        "",
        "## Raw Data Used",
        "```json",
        json.dumps(data.get("ratios", {}), indent=2),
        "```",
        "",
        "## Shareholding",
        "```json",
        json.dumps(data.get("shareholding", {}), indent=2),
        "```",
        "",
        "---",
        "*Generated by Hybrid Stock Analyst (HSA)*"
    ]

    return "\n".join(lines)


def save_report(symbol: str, result: dict, data: dict) -> Path:
    """Save analysis as a markdown file to output/reports."""
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_path = REPORTS_DIR / f"{symbol.upper()}_{ts}.md"
    content = generate_report_markdown(symbol, result, data)
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"[Report] Saved to: {report_path}")
    return report_path


def show_ledger():
    """Print portfolio ledger from local JSON files."""
    LEDGER_DIR.mkdir(parents=True, exist_ok=True)
    ledger_file = LEDGER_DIR / "portfolio.json"

    if not ledger_file.exists():
        print("[Ledger] No positions found. Use 'add-position' to add a trade.")
        return

    with open(ledger_file, encoding="utf-8") as f:
        portfolio = json.load(f)

    positions = portfolio.get("positions", [])
    if not positions:
        print("[Ledger] No open positions.")
        return

    print("\n" + "="*70)
    print("  PORTFOLIO LEDGER")
    print("="*70)
    print(f"  {'Symbol':<12} {'Entry':>8} {'Qty':>5} {'SL':>8} {'Target':>8} {'Status':<10}")
    print("-"*70)
    for p in positions:
        print(f"  {p.get('symbol',''):<12} {p.get('entry_price',0):>8.2f} "
              f"{p.get('quantity',0):>5} {p.get('stop_loss',0):>8.2f} "
              f"{p.get('target',0):>8.2f} {p.get('status','Open'):<10}")
    print("="*70 + "\n")


def add_position(symbol: str, entry_price: float, quantity: int):
    """Add a position to the local ledger JSON."""
    LEDGER_DIR.mkdir(parents=True, exist_ok=True)
    ledger_file = LEDGER_DIR / "portfolio.json"

    portfolio = {"positions": []}
    if ledger_file.exists():
        with open(ledger_file, encoding="utf-8") as f:
            portfolio = json.load(f)

    stop_loss = round(entry_price * 0.93, 2)   # 7% stop-loss rule
    target = round(entry_price * 1.21, 2)       # 21% target (3:1 R/R approx)

    position = {
        "symbol": symbol.upper(),
        "entry_price": entry_price,
        "entry_date": datetime.now().strftime("%Y-%m-%d"),
        "quantity": quantity,
        "stop_loss": stop_loss,
        "target": target,
        "current_price": entry_price,
        "status": "Open"
    }

    # Update if exists, else append
    positions = portfolio.get("positions", [])
    existing = [p for p in positions if p["symbol"] == symbol.upper()]
    if existing:
        idx = positions.index(existing[0])
        positions[idx] = position
    else:
        positions.append(position)

    portfolio["positions"] = positions

    with open(ledger_file, "w", encoding="utf-8") as f:
        json.dump(portfolio, f, indent=2)

    print(f"\n[Ledger] Position added:")
    print(f"  {symbol.upper()} | Entry: Rs.{entry_price} | Qty: {quantity}")
    print(f"  Stop-Loss: Rs.{stop_loss} (-7%) | Target: Rs.{target} (+21%)")
    print(f"  Max Loss: Rs.{round((entry_price - stop_loss) * quantity, 2)}")
    print(f"  Max Profit: Rs.{round((target - entry_price) * quantity, 2)}\n")


# ── Main Analysis Flow ────────────────────────────────────────────────────────

async def run_tijori_skill(symbol: str, force_login: bool = False, deep: bool = False) -> dict:
    """
    Run the Tijori skill scraper (full multi-tab extraction).
    If registry doesn't exist, runs explorer first.
    Falls back to basic scraper if skill fails.
    """
    import subprocess
    import sys as _sys

    if force_login or not TIJORI_REGISTRY.exists():
        print(f"  [Tijori] Running explorer first (registry missing or --login requested)...")
        proc = await asyncio.create_subprocess_exec(
            _sys.executable, str(TIJORI_EXPLORE), symbol,
            cwd=str(BASE_DIR / "skills" / "tijori" / "scripts")
        )
        await proc.wait()

    # Run the production scraper
    print(f"  [Tijori] Running production scraper (all tabs)...")
    sys.path.insert(0, str(BASE_DIR / "skills" / "tijori" / "scripts"))
    try:
        from scrape_tijori import run_scraper
        data = await run_scraper(symbol, deep=deep)
        return data
    except Exception as e:
        print(f"  [Tijori] Skill scraper failed: {e}. Falling back to basic scraper...")
        from scraper import TijoriScraper
        scraper = TijoriScraper(symbol, force_login=False)
        data = await scraper.run()
        scraper.save()
        return data


async def run_analysis(symbol: str, portfolio_value: float = None, force_login: bool = False, demo: bool = False, deep: bool = False, enrich: bool = False):
    """Full analysis pipeline: Scrape -> Evaluate -> Sync -> Report."""
    symbol = symbol.upper()
    print(f"\n{'='*60}")
    print(f"  HYBRID STOCK ANALYST - Analyzing: {symbol}")
    print(f"  {'[DEMO MODE - No browser]' if demo else '[LIVE MODE - Browser will open]'}")
    print(f"{'='*60}\n")

    # -- Phase 1: Data Acquisition --------------------------------------------------
    print("[PHASE 1] Data Acquisition")
    if demo:
        print("  Loading mock demo data...")
        data = load_mock_data(symbol)
    else:
        # Try loading existing bundle first (from today)
        existing = load_latest_bundle(symbol)
        if existing:
            scraped_date = existing.get("scraped_at", "")[:10]
            today = datetime.now().strftime("%Y-%m-%d")
            if scraped_date == today and not force_login and (not deep or "knowledge_base_text" in existing):
                print(f"  Using today's cached data (scraped at {existing['scraped_at'][:19]})")
                data = existing
            else:
                data = await run_tijori_skill(symbol, force_login, deep=deep)
        else:
            data = await run_tijori_skill(symbol, force_login, deep=deep)

        if enrich:
            print("\n  [Enrich] Fetching price data and technical indicators from Upstox...")
            try:
                from upstox_auth import UpstoxAuth
                from upstox_client import UpstoxClient
                from price_enricher import PriceEnricher

                auth = UpstoxAuth()
                client = UpstoxClient(auth)
                
                # Resolve symbol to instrument key
                key = client.resolve_instrument_key(symbol)
                
                # Fetch daily candles (365 days)
                candles = client.fetch_daily_candles(key, days=365)
                
                if candles:
                    enricher = PriceEnricher(candles, symbol=symbol)
                    price_data = enricher.enrich_price_data()
                    
                    # Update data bundle's price_data
                    data["price_data"] = price_data
                    
                    # Overwrite/save the bundle to cache so it has the enriched data
                    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
                    bundle_path = BUNDLES_DIR / f"{symbol.upper()}_{ts}.json"
                    BUNDLES_DIR.mkdir(parents=True, exist_ok=True)
                    with open(bundle_path, "w", encoding="utf-8") as f:
                        json.dump(data, f, indent=2)
                    print(f"  [Enrich] Enriched data bundle saved to: {bundle_path}")
                else:
                    print("  [Enrich] [WARN] No candles fetched. Keeping existing/null price data.")
            except Exception as e:
                print(f"  [Enrich] [ERR] Price enrichment failed: {e}")

    # -- Phase 2: Rule Evaluation (Python Math) ------------------------------------
    print("\n[PHASE 2] Rule Evaluation (Local Math Engine)")
    engine = RuleEngine(symbol, data)
    result = engine.evaluate()
    engine.print_report()

    # Position sizing if portfolio value provided
    if portfolio_value:
        current_price = data.get("price_data", {}).get("current_price")
        if current_price:
            sizing = engine.calculate_position(portfolio_value, float(current_price))
            print("  POSITION SIZING:")
            for k, v in sizing.items():
                print(f"     {k}: {v}")

    # -- Phase 3: Memory & Sync ----------------------------------------------------
    print("\n[PHASE 3] Saving Memory & Syncing to Notion")
    mem_path = engine.save_memory()
    report_path = save_report(symbol, result, data)

    notion = NotionSync()
    if notion.is_connected():
        page_url = notion.upsert_stock_analysis(result)
        if page_url:
            print(f"  [Notion] Page: {page_url}")

    print(f"\n[DONE] Analysis Complete!")
    print(f"  Memory: {mem_path}")
    print(f"  Report: {report_path}")
    print()

    # -- Phase 4: Context for Antigravity (LLM) ------------------------------------
    # This block outputs a structured prompt that Antigravity reads when this
    # script is called from within a conversation. The LLM then gives the
    # qualitative synthesis that Python can't do (sector context, news, macro).
    print("[LLM CONTEXT] ANTIGRAVITY SYNTHESIS CONTEXT:")
    print("-"*60)
    print(f"Symbol: {symbol}")
    print(f"Score: {result['score']}/100 | Verdict: {result['verdict']}")
    print(f"Trend: {result['trend_score']} | Fundamentals: {result['fundamental_score']} | Technicals: {result['technical_score']}")
    print(f"Strengths: {', '.join(result.get('strengths', [])) or 'None'}")
    print(f"Weaknesses: {', '.join(result.get('weaknesses', [])) or 'None'}")
    print(f"Risk Flags: {'; '.join(result.get('risk_flags', [])) or 'None'}")
    print("-"*60)
    print("Antigravity: Please provide qualitative synthesis - sector outlook,")
    print("recent news impact, macro environment relevance, and final recommendation.")
    print("-"*60 + "\n")

    return result


# ── CLI Entry Point ───────────────────────────────────────────────────────────

def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(0)

    command = sys.argv[1].lower()

    if command in ("analyze", "analyse"):
        if len(sys.argv) < 3:
            print("Usage: python src/main.py analyze <SYMBOL> [--portfolio <value>] [--login] [--fresh] [--enrich]")
            sys.exit(1)
        symbol = sys.argv[2]
        portfolio = None
        force_login = "--login" in sys.argv
        demo = "--demo" in sys.argv
        deep = "--deep" in sys.argv
        enrich = "--enrich" in sys.argv
        if "--portfolio" in sys.argv:
            idx = sys.argv.index("--portfolio")
            try:
                portfolio = float(sys.argv[idx + 1])
            except (IndexError, ValueError):
                print("Invalid portfolio value.")
                sys.exit(1)

        asyncio.run(run_analysis(symbol, portfolio_value=portfolio, force_login=force_login, demo=demo, deep=deep, enrich=enrich))

    elif command == "demo":
        symbol = sys.argv[2] if len(sys.argv) > 2 else "DEMO"
        asyncio.run(run_analysis(symbol, demo=True))

    elif command == "ledger":
        show_ledger()

    elif command == "add-position":
        if len(sys.argv) < 5:
            print("Usage: python src/main.py add-position <SYMBOL> <ENTRY_PRICE> <QUANTITY>")
            sys.exit(1)
        symbol = sys.argv[2]
        entry_price = float(sys.argv[3])
        quantity = int(sys.argv[4])
        add_position(symbol, entry_price, quantity)

    elif command == "watchlist":
        # Show all stocks in memory/stocks/
        stocks_dir = MEMORY_DIR / "stocks"
        stocks_dir.mkdir(parents=True, exist_ok=True)
        files = list(stocks_dir.glob("*.json"))
        if not files:
            print("[Watchlist] No stocks analyzed yet. Run: python src/main.py analyze <SYMBOL>")
            return
        print("\n" + "="*60)
        print("  ANALYZED STOCKS MEMORY")
        print("="*60)
        for f in sorted(files):
            with open(f, encoding="utf-8") as fp:
                d = json.load(fp)
            last = d.get("last_analysis", {})
            history = d.get("history", [])
            symbol = d.get("symbol", f.stem)
            score = last.get("score", "?")
            verdict = last.get("verdict", "?")
            date = last.get("evaluated_at", "?")[:10]
            count = len(history)
            print(f"  {symbol:<12} | {verdict:<20} | Score: {score:>5} | Analyzed: {date} | History: {count}x")
        print("="*60 + "\n")

    else:
        print(f"Unknown command: {command}")
        print("Available: analyze, demo, ledger, add-position, watchlist")
        sys.exit(1)


if __name__ == "__main__":
    main()
